export type IStringKey = Record<string, any>

export type TextSizeType =
  | 'h1'
  | 'h1_b'
  | 'h2'
  | 'h2_b'
  | 'h3'
  | 'h3_b'
  | 'h4'
  | 'h4_b'
  | 'h5'
  | 'h5_b'
  | 'h6'
  | 'h6_b'
  | 'b1'
  | 'b1_b'
  | 'b2'
  | 'b2_b'
  | 'c'
  | 'c_b'

export type ColorType =
  | 'primary100'
  | 'primary200'
  | 'primary300'
  | 'primary400_main'
  | 'primary500'
  | 'primary600'
  | 'primary700'
  | 'primary800'
  | 'secondary100'
  | 'secondary200'
  | 'secondary300'
  | 'secondary400_main'
  | 'secondary500'
  | 'secondary600'
  | 'secondary700'
  | 'side100'
  | 'side200'
  | 'side300'
  | 'side400'
  | 'side500'
  | 'logo'
  | 'error100'
  | 'error200'
  | 'error300'
  | 'error400'
  | 'error500'
  | 'gray0'
  | 'gray1'
  | 'gray2'
  | 'gray3'
  | 'gray4'
  | 'gray5'
  | 'gray6'
  | 'gray7'
  | 'gray8'
  | 'black'

export type IconType =
  | 'warning'
  | 'xcircle'
  | 'heart'
  | 'check'
  | 'arrowleft'
  | 'arrowright'
  | 'male'
  | 'female'
  | 'bellringing'
  | 'caretup'
  | 'caretdown'
  | 'graduationcap'
  | 'handshake'
  | 'health'
  | 'values'
  | 'magnet'
  | 'pen'
  | 'bagpack'
  | 'briefcase'
  | 'cookpot'
  | 'smiley'

export type DropdownType = 'year' | 'month' | 'day' | 'mbti'
